version: "3.8"

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8080:3000"
    networks:
      - app-network

  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - app-network
    command: redis-server --bind 0.0.0.0 --appendonly yes --appendfsync everysec

  redis-insight:
    image: redis/redisinsight:latest
    restart: always
    ports:
      - "5540:5540"
    volumes:
      - redis-insight:/data
    networks:
      - app-network

volumes:
  redis-data:
  redis-insight:

networks:
  app-network:
    driver: bridge
